### ISSUE TITLE
is it work with statistics

### ISSUE THREAD

**Issue by progfiles** [YasuakiHonda/Maxima-on-Android-AS#7]
I try this code
`a:[1.2,3,5,1.2,4.5,4,8,9,4,5,1,3,4,7,12,8,9,5,4,6];
mean(a);`
It is work on PC but not in android.

Is it work with statistics?

**Comment by YasuakiHonda** [comment]
It does work, but you need to perform:
load ("descriptive");
before using mean().

2018/01/25 2:34 "Alexey" <notifications@github.com>:
